apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-microproject-deployment
  labels:
    app: k8s-microproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-microproject
  template:
    metadata:
      labels:
        app: k8s-microproject
    spec:
      containers:
        - name: microproject
          image: claquetteuuuh/k8s-microproject
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: k8s-microproject-config
          volumeMounts:
            - name: project-storage
              mountPath: /usr/src/app/data
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
      volumes:
        - name: project-storage
          persistentVolumeClaim:
            claimName: k8s-microproject-pvc